// Dummy Data for Demo Presentation

export const dashboardStats = {
  sales: {
    newLeads: 12,
    followUpsToday: 8,
    meetings: 3,
    proposalsPending: 5,
    pipelineValue: 2500000,
    expectedRevenue: 1800000,
  },
  operations: {
    activeProjects: 18,
    delayedProjects: 3,
    tasksOverdue: 12,
    contentAwaitingApproval: 9,
    upcomingShoots: 4,
  },
  finance: {
    revenue: 850000,
    collections: 650000,
    outstanding: 450000,
    overduePayments: 180000,
    expectedCashflow: 920000,
  },
  team: {
    workload: 85,
    overdueTasks: 12,
    projectAllocation: "High",
  },
};

export const myAttentionItems = [
  {
    id: 1,
    title: "ABC Corp payment overdue by 15 days",
    priority: "critical",
    amount: "₹2,50,000",
    type: "payment",
  },
  {
    id: 2,
    title: "XYZ Brand project deadline tomorrow - 3 tasks incomplete",
    priority: "urgent",
    type: "project",
  },
  {
    id: 3,
    title: "High-value lead (₹5L) not contacted in 6 days",
    priority: "high",
    client: "TechStart Solutions",
    type: "lead",
  },
  {
    id: 4,
    title: "Shoot tomorrow - Equipment checklist pending",
    priority: "urgent",
    location: "Mumbai Studio",
    type: "shoot",
  },
  {
    id: 5,
    title: "7 content pieces awaiting client approval (blocking publish)",
    priority: "medium",
    type: "content",
  },
];

export const leads = [
  {
    id: "1",
    stage: "new",
    company: "TechStart Solutions",
    contact: "Rahul Sharma",
    source: "Instagram",
    value: 500000,
    priority: "high",
    nextFollowUp: "2026-09-10",
  },
  {
    id: "2",
    stage: "contacted",
    company: "Fitness Hub",
    contact: "Priya Patel",
    source: "Referral",
    value: 250000,
    priority: "medium",
    nextFollowUp: "2026-09-12",
  },
  {
    id: "3",
    stage: "qualified",
    company: "Urban Cafe",
    contact: "Amit Verma",
    source: "Website",
    value: 150000,
    priority: "medium",
    nextFollowUp: "2026-09-11",
  },
  {
    id: "4",
    stage: "meeting",
    company: "Fashion Forward",
    contact: "Sneha Kapoor",
    source: "Instagram",
    value: 800000,
    priority: "high",
    nextFollowUp: "2026-09-09",
  },
  {
    id: "5",
    stage: "proposal",
    company: "EduTech Academy",
    contact: "Vikram Singh",
    source: "Cold Outreach",
    value: 350000,
    priority: "medium",
    nextFollowUp: "2026-09-13",
  },
  {
    id: "6",
    stage: "negotiation",
    company: "Luxury Stays",
    contact: "Neha Gupta",
    source: "Referral",
    value: 600000,
    priority: "high",
    nextFollowUp: "2026-09-10",
  },
];

export const projects = [
  {
    id: "1",
    name: "Q4 Brand Campaign",
    client: "ABC Corporation",
    status: "in-production",
    progress: 65,
    deadline: "2026-09-20",
    budget: 500000,
    team: ["Karthik", "Priya", "Amit"],
    tasksTotal: 24,
    tasksCompleted: 16,
  },
  {
    id: "2",
    name: "Product Launch Videos",
    client: "XYZ Brand",
    status: "editing",
    progress: 80,
    deadline: "2026-09-10",
    budget: 350000,
    team: ["Saksham", "Rahul"],
    tasksTotal: 15,
    tasksCompleted: 12,
  },
  {
    id: "3",
    name: "Social Media Content - Sep",
    client: "Fitness Hub",
    status: "client-review",
    progress: 90,
    deadline: "2026-09-15",
    budget: 180000,
    team: ["Priya", "Neha"],
    tasksTotal: 30,
    tasksCompleted: 27,
  },
];

export const contentPipeline = [
  {
    id: "1",
    stage: "idea",
    title: "Diwali Campaign Concept",
    client: "ABC Corp",
    platform: "Instagram",
    deadline: "2026-09-15",
  },
  {
    id: "2",
    stage: "script",
    title: "Product Demo Video",
    client: "XYZ Brand",
    platform: "YouTube",
    deadline: "2026-09-12",
  },
  {
    id: "3",
    stage: "shoot",
    title: "Testimonial Series",
    client: "Fitness Hub",
    platform: "Instagram",
    deadline: "2026-09-11",
  },
  {
    id: "4",
    stage: "editing",
    title: "Reel - New Launch",
    client: "Fashion Forward",
    platform: "Instagram",
    deadline: "2026-09-13",
  },
  {
    id: "5",
    stage: "client-review",
    title: "Tutorial Video",
    client: "EduTech",
    platform: "YouTube",
    deadline: "2026-09-10",
  },
  {
    id: "6",
    stage: "approved",
    title: "Brand Story",
    client: "Luxury Stays",
    platform: "Instagram",
    deadline: "2026-09-14",
  },
];

export const calendarEvents = [
  { date: "2026-09-09", title: "ABC Corp - Brand Video", status: "scheduled" },
  { date: "2026-09-10", title: "XYZ Brand - Product Launch", status: "scheduled" },
  { date: "2026-09-11", title: "Fitness Hub - Workout Reel", status: "published" },
  { date: "2026-09-12", title: "Fashion Forward - Collection Post", status: "scheduled" },
  { date: "2026-09-13", title: "EduTech - Tutorial Series", status: "scheduled" },
];

export const invoices = [
  {
    id: "INV-001",
    client: "ABC Corporation",
    amount: 500000,
    gst: 90000,
    total: 590000,
    received: 590000,
    balance: 0,
    status: "paid",
    dueDate: "2026-09-05",
  },
  {
    id: "INV-002",
    client: "XYZ Brand",
    amount: 350000,
    gst: 63000,
    total: 413000,
    received: 200000,
    balance: 213000,
    status: "partial",
    dueDate: "2026-09-15",
  },
  {
    id: "INV-003",
    client: "Fitness Hub",
    amount: 180000,
    gst: 32400,
    total: 212400,
    received: 0,
    balance: 212400,
    status: "overdue",
    dueDate: "2026-08-25",
  },
];

export const profitabilityData = [
  {
    client: "ABC Corporation",
    revenue: 1500000,
    cost: 900000,
    profit: 600000,
    margin: 40,
  },
  {
    client: "XYZ Brand",
    revenue: 800000,
    cost: 650000,
    profit: 150000,
    margin: 18.75,
  },
  {
    client: "Fitness Hub",
    revenue: 500000,
    cost: 350000,
    profit: 150000,
    margin: 30,
  },
  {
    client: "Fashion Forward",
    revenue: 1200000,
    cost: 720000,
    profit: 480000,
    margin: 40,
  },
];

export const revenueChartData = [
  { month: "Mar", revenue: 420000, profit: 180000 },
  { month: "Apr", revenue: 580000, profit: 240000 },
  { month: "May", revenue: 650000, profit: 290000 },
  { month: "Jun", revenue: 720000, profit: 310000 },
  { month: "Jul", revenue: 850000, profit: 380000 },
  { month: "Aug", revenue: 920000, profit: 420000 },
];
